### PR TITLE
Add laplaceFromSample method.

### PR DESCRIPTION
**Pull request by mihaimaruseac**
Allows estimating the parameters of a Laplace distribution based on
a sample (location is the sample median and scale is the average
mean deviation from the location). No checks are made to test that
the sample comes from a Laplace distribution.

With this, the Statistics.Distribution.Laplace module closely mimics the
Statistics.Distribution.Exponential one.

### CODE REVIEW

**Comment by mihaimaruseac** [comment]
This solves all the remaining issues with the implementation in `Statistics.Distribution.Laplace`, at least to the best of my current understanding of the architecture of the package.

**Comment by Shimuuar** [comment]
Thank you! I don't have time right now so I'll review it after weekends.

**Comment by mihaimaruseac** [comment]
Hi.

Did you find some time to look through it? Do I need to do more/is the implementation wrong?

**Comment by Shimuuar** [comment]
Sorry for delay. PR is OK but we have problem with bitbucket<->github mirroring so I couldn't merge it.

**Comment by mihaimaruseac** [comment]
Should I try to push it to bitbucket then?

**Comment by Shimuuar** [comment]
No repo on bitbucket is borked at the moment too :(

**Comment by Shimuuar** [comment]
Rebased and merged, thank you!

Sorry it did take a long time

**Pull request closed without merging**
