### PR TITLE
Base orphans 0.8

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by Shimuuar** [comment]
I cherry-picked bump to base-orphans and pushed to master. I tweaked .travis.yml by hand so I'll need to recheck whether generated file actually works

**Comment by 23Skidoo** [comment]
Would be nice if you could also do a Hackage revision.

**Comment by Shimuuar** [comment]
Actually I was done for 0.14.0.2 in March http://hackage.haskell.org/package/statistics-0.14.0.2/revisions/ and then I forgot to update cabal in repo

**Comment by 23Skidoo** [comment]
/me has only just noticed that this PR bumps the upper bound to `< 0.8`, not `< 0.9`.

`base-orphans-0.8` is now out as well, and appears to work fine with `statistics-0.14.0.2`, so it'd be nice if you could bump the upper bound to `< 0.9`.

**Comment by Shimuuar** [comment]
@23Skidoo CI is green so I changed version bound on hackage

**Comment by 23Skidoo** [comment]
Great, thanks!

**Comment by phadej** [comment]
Thanks! I didn't noticed that I bumped too little, sorry for the confusion.

**Pull request closed without merging**
