### PR TITLE
Split out dense-linear-algebra

### PR DESCRIPTION
**Pull request by ocramz**

### CODE REVIEW

**Comment by ocramz** [comment]
@Shimuuar ping ! :)

**Comment by Shimuuar** [comment]
Today is first day when I can do something after night flight. Will take a look in the evening

**Comment by ocramz** [comment]
@Shimuuar ping! :) :)

**Comment by Shimuuar** [comment]
I finally started looking into it. I was right about splitting exponent part it doesn't work for matrices of general form, only for ones that appear in K-S test.

**Comment by Shimuuar** [comment]
I finally merged it. Overflow handling logic now in K-S test and I also moved `S.Function` & `S.Sample.Internal` back to statistics they aren't strictly related to linear algebra and will introduce unneeded dependency

**Comment by ocramz** [comment]
Thank you so much @Shimuuar ! 🙏

**Pull request merged**
