### PR TITLE
Got test suite compiling and running again

### PR DESCRIPTION
**Pull request by axch**
by updating the relevant tests to the new APIs of the Student T, Mann-Whitney, Wilcoxon, and Kruskal-WIllis tests.

### CODE REVIEW

**Comment by Shimuuar** [comment]
Thank you!

We had problem with HG <-> git mirroring (as you can see history is terribly convoluted). It was fixed  and commit which caused breakage of test were removed from master repo. They still could be found in my fork. I will review this later

**Comment by axch** [comment]
Hm.  Looking at what Github says the history is now, I'm guessing that merging this particular pull request may not be worth the trouble, but I will leave that to you to decide.

**Comment by Shimuuar** [comment]
I will look into it when I'll try to finish new test API

**Comment by Shimuuar** [comment]
Test suite was fixed long time ago. So I guess this PR is not going to merged. But thank you anyway.

**Pull request closed without merging**
