### PR TITLE
Added standardize normalization technique.

### PR DESCRIPTION
**Pull request by GregorySchwartz**

### CODE REVIEW

**Comment by GregorySchwartz** [comment]
1. That can be added to.

2. Both cases are the same: the population is constant and not a variable, so the standard normalization is not applicable (return NaN or Nothing).

3. I made a new module because I believe there should be a wide variety of different normalization techniques here. Some easy, necessary ones to add would be upper quartile normalization, median normalization, quantile normalization (https://en.wikipedia.org/wiki/Quantile_normalization), and min max feature scaling (https://en.wikipedia.org/wiki/Feature_scaling).

**Comment by Shimuuar** [comment]
1. Please improve documentation. It should explain what excetly function do

2. In that case it's probably best to change function signature to `v Double → Maybe (v Double)`. I dislike returning NaNs. They propagate quickly and it's difficult to pinpoint their origin

3. Sounds reasonable

**Comment by GregorySchwartz** [comment]
2. Ah, I didn't know the stance of that in the library. I should then point out some of these I ran into (in a separate issue).

**Comment by Shimuuar** [comment]
Library is _very_ inconsistent about this. See #100 for more details

**Comment by Shimuuar** [comment]
I think we should just return `Nothing` in case when normalization is impossible.

**Comment by Shimuuar** [comment]
Rebased and merged. Thank you!

After some considerations I made `standardize` function return `Nothing` if σ couldn't be computed or equal to zero

**Pull request closed without merging**
