### PR TITLE
Add Laplace distribution and tests for it.

### PR DESCRIPTION
**Pull request by mihaimaruseac**
I use this distribution on my research (on differential privacy) and it's becoming cumbersome to use the difference of two exponential variates to generate such a random variable.

Needs further code for generating a distribution from a sample. I didn't do it because it also requires adding median to Sample.

Furthermore, I saw some more improvements of the package that can be made, if possible I'll do them over the next weeks, in my spare time, if that's OK.

Thanks.

### CODE REVIEW

**Comment by Shimuuar** [comment]
PR looks find on first glance. It will review and merge it tomorrow.

Median estimator could be found in `Statistics.Quantile` and documentation of `Statistics.Sample` doesn't mention it.

**Comment by mihaimaruseac** [comment]
Thanks. I'll implement the estimator over the weekend or next week.

**Comment by Shimuuar** [comment]
Merged! Only issue was loss of precision for the `cumulative` and `conplCumulative` for small p. They we calculated as `0.5 - almost 0.5` which leads to the precision loss. I'm not uploading this to hackage since you're going to submit another PR

Thank you for contribution!

**Comment by mihaimaruseac** [comment]
I'll think of a way to solve that too. I'll submit new code over the weekend. Thanks.

**Comment by Shimuuar** [comment]
I've already fixed issues with numerical accuracy

**Comment by mihaimaruseac** [comment]
That's nice, thanks.

**Pull request merged**
