### PR TITLE
Fix some warnings (redundant imports, name shadowing)

### PR DESCRIPTION
**Pull request by intricate**

### CODE REVIEW

**Comment by intricate** [comment]
@Shimuuar: Is this PR of any use? :smile: Obviously it's nothing significant, but...

**Comment by Shimuuar** [comment]
Sorry for the delay. I was quite busy lately. I'll look at it over weekend

**Comment by Shimuuar** [comment]
I finally tried to do something about this PR. Problem is I'm sure it breaks build on some old GHC, but I'm unable to test it since tests are broken. So I'm leaving it hanging while I try to fix test suite

**Comment by intricate** [comment]
> I finally tried to do something about this PR. Problem is I'm sure it breaks build on some old GHC, but I'm unable to test it since tests are broken. So I'm leaving it hanging while I try to fix test suite

Gotcha.

**Comment by Shimuuar** [comment]
I cherry picked commit which fixed shadowing warning. Others quite predictably broken GHC<=7.8.

**Comment by intricate** [comment]
> I cherry picked commit which fixed shadowing warning. Others quite predictably broken GHC<=7.8.

Thanks! I'll try building this branch on older GHC versions just to confirm and then I'll close the PR. :smiley:

**Comment by Shimuuar** [comment]
Here is CI run with failures
https://travis-ci.org/Shimuuar/statistics/builds/632388942

**Comment by intricate** [comment]
Gotcha. We'll just close this PR then. Thanks for taking the time.

**Comment by Shimuuar** [comment]
So I dropped GHC<7.10 and this PR finally found its way into master

**Pull request closed without merging**
