### PR TITLE
No monad-par

### PR DESCRIPTION
**Pull request by phadej**
- A follow-up to #153
- This is breaking change, thus bump to 0.16.0.0

### CODE REVIEW

**Comment by phadej** [comment]
Travis finds an error, doesn't seem to be flacky test as it fals for all: https://travis-ci.org/phadej/statistics/builds/581223110

**Comment by phadej** [comment]
```
    Quantile is CDF inverse: [Failed]
*** Failed! Falsified (after 74 tests):
improperBetaDistr 6.066879774862245 2.1580596992700846e-2
Double01 0.4738491705022376
Quantile      = 0.9999999999966989
Probability   = 0.4738491705022376
Probability'  = 0.406265193062443
Expected err. = 1.1640522432234172e-4
Rel. error    = 0.1426276158047542
Abs. error    = 6.75839774397946e-2
(used seed -1941437610513804096)
```

```
    Quantile is CDF inverse: [Failed]
*** Failed! Falsified (after 38 tests):
studentT 23.94048025867691
Double01 0.5140747169561415
Quantile      = 3.565819084774477e-2
Probability   = 0.5140747169561415
Probability'  = 0.5140747169561308
Expected err. = 1.459975822613828e-14
Rel. error    = 2.0732669172117263e-14
Abs. error    = 1.0658141036401503e-14
(used seed 896595580385502909)
```

and discrete cdf too.

**Comment by Shimuuar** [comment]
Yes. Well known issue: #123. It's not clear whether it's bug in statistics or bug in test. Testing numeric code is always difficult since answer is only approximately correct and it's difficult to quantify precison. Especially because frequently there're corners in parameter space where precision is lost no matter what

**Comment by phadej** [comment]
@Shimuuar yes, `master` seems to work.

Related to #123, it fails /every/ time on my machine, which is super annoying. In https://www.youtube.com/watch?v=NcJOiQlzlXQ John Hughes shows not-so-common used features QuickCheck, so with `label` etc. you can understand the generator and your tests better.

**Comment by Shimuuar** [comment]
Great! I'll make a release then

Thanks for label. I didn't know about it. 

Test failure are very annoyting, true. Also tests used to fail only now and then. I guess QC became better at exploring Double parameters. Hardest part of fixing them is producing error estimate. It require a bit of calculus and a lot of plotting. Example plot with error estimate and actual error:
work2

I started overhauling math-functions's test suite. In some indeterminate time in the future I hope I'll get to statistics test suite as well.

**Comment by phadej** [comment]
@Shimuuar thanks!

**Comment by Shimuuar** [comment]
statistics 0.15.1.0 is on hackage. Hopefully everything should work

**Pull request closed without merging**
